module:cluster:
- sklearn_fork/cluster/**/*

module:common:
- sklearn_fork/common/**/*

module:compose:
- sklearn_fork/compose/**/*

module:covariance:
- sklearn_fork/covariance/**/*

module:cross_decomposition:
- sklearn_fork/cross_decomposition/**/*

module:datasets:
- sklearn_fork/datasets/**/*

module:decomposition:
- sklearn_fork/decomposition/**/*

module:ensemble:
- sklearn_fork/ensemble/**/*

module:feature_extraction:
- sklearn_fork/feature_extraction/**/*

module:feature_selection:
- sklearn_fork/feature_selection/**/*

module:gaussian_process:
- sklearn_fork/gaussian_process/**/*

module:impute:
- sklearn_fork/impute/**/*

module:inspection:
- sklearn_fork/inspection/**/*

module:linear_model:
- sklearn_fork/linear_model/**/*

module:manifold:
- sklearn_fork/manifold/**/*

module:metrics:
- sklearn_fork/metrics/**/*

module:mixture:
- sklearn_fork/mixture/**/*

module:model_selection:
- sklearn_fork/model_selection/**/*

module:naive_bayes:
- sklearn_fork/naive_bayes.py

module:neighbors:
- sklearn_fork/neighbors/**/*

module:neural_network:
- sklearn_fork/neural_network/**/*

module:pipeline:
- sklearn_fork/pipeline.py

module:preprocessing:
- sklearn_fork/preprocessing/**/*

module:semi_supervised:
- sklearn_fork/semi_supervised/**/*

module:svm:
- sklearn_fork/svm/**/*

module:tree:
- sklearn_fork/tree/**/*

module:utils:
- sklearn_fork/utils/**/*
